# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b992d29d5a3bca301c73cd783ce0009aa5125484822d17323111952e18312c809131146210e76efaaa12dbee2c7a424ef5a20cf2e82e78035a2769b8a0e0e17c

test:
  secret_key_base: 932bea42c1ba7df650acccc3100d13698c8d3a737d6e447254127f4057d737fa9269db072a6f9d1e4e64acd982b5010bb518f1b1fbfa3f37d96ad429458b2575

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
